In [ ]:
#陣列屬性
import numpy as np

x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

#維度(ndim),每個維度大小(shape),整個陣列大小(size)
print("x3 ndim:",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)

#知道該陣列之屬性
print("x3 dtype:",x3.dtype)

#元素屬性(itemsize),陣列大小(nbytes)
print("x3 itemsize:",x3.itemsize)
print("x3 nbytes:",x3.nbytes)

In [ ]:
#陣列索引:存取單一的陣列元素
import numpy as np

#跟list類似
x1=np.random.randint(10,size=6)
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

x2=np.random.randint(10,size=(3,4))
print(x2)
print(x2[0,0])
print(x2[2,3])
print(x2[2,-1])

x2[0,0]=12 #更改陣列內容
print(x2)

#因為NumPy的陣列元素必須是單一型態，所以浮點數就會變成整數
x1[0]=3.1415926
print(x1)

In [ ]:
#陣列切片:存取子陣列
import numpy as np

#一維子陣列
x1=np.arange(10)
print(x1)

#[start:stop:step]，stop點不會輸出
print(x1[:5])#前面5個元素
print(x1[5:])#index5以後
print(x1[4:7])#index4 to index7(not output)
print(x1[::2])#間格2的所有元素
print(x1[1::2])#index1開始間隔為2的所有元素
print(x1[::-1])#反轉取得陣列
print(x1[5::-2])#index5開始反轉輸出間格為2的數

#多維子陣列
x2=np.random.randint(10,size=(3,4))
print(x2)

#方法類似1維
print(x2[:2,:3])#2列3行
print(x2[:3,::2])#3列,行為間格2
print(x2[::-1,::-1])#反轉全部的元素
print(x2[:,0])#第一行
print(x2[0,:])#第一列
print(x2[0])#也可以直接省略空白處

#取出的切片為實際的內容(陣列視圖typed array view)，而非透過複製而成的
print(x2)
x2_sub=x2[:2,:2]
print(x2_sub)
x2_sub[0,0]=99 #所以對切片內容改寫,也會改到實際原本array內容
print(x2_sub)
print(x2)

#有時仍需要複製出資料
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0]=42
print(x2_sub_copy)
print(x2)

In [ ]:
#陣列重塑(reshape)
import numpy as np

grid=np.arange(1,10)
print(grid)
grid=np.arange(1,10).reshape(3,3) #將數字1到9放入3*3之陣列grid中
print(grid)

#利用reshape建立1*3之列向量
x1=np.array([1,2,3]).reshape(1,3)
print(x1)
#newaxis直接在切片當中使用
x2=np.array([1,2,3])[np.newaxis,:]
print(x2)
#利用reshape建立3*1之行向量
x3=np.array([1,2,3]).reshape(3,1)
print(x3)
#newaxis直接在切片當中使用
x4=np.array([1,2,3])[:,np.newaxis]
print(x4)



In [ ]:
#陣列的串接和分割
import numpy as np

#串接
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([99,99,99])

#x和y串接
xy=np.concatenate([x,y])
print(xy)
#x和y和z串接
xyz=np.concatenate([x,y,z])
print(xyz)

#二維上的串接
grid=np.array([[1,2,3],
       [4,5,6]])
print(grid)
#concatenate必須要陣列為相同的維度
#沿著第一個軸串接(axis=0可以省略不寫)
newGrid1=np.concatenate([grid,grid])
print(newGrid1)
#沿著第二個軸串接
newGrid2=np.concatenate([grid,grid],axis=1)
print(newGrid2)

#不同維度,可以利用vstack和hstack
#垂直堆疊在陣列上
newGrid3=np.vstack([z,grid])
print(newGrid3)
#水平堆疊於陣列上  #注意要記得列數要一樣
newZ=np.array([[99],
       [99]])
newGrid4=np.hstack([grid,newZ])
print(newGrid4)

#分割
#N個分割點會N+1個子陣列
#split
x=[1,2,3,99,99,3,2,1]
print(x)
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)
#vsplit
grid=np.arange(16).reshape(4,4)
print(grid)
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)
#hsplit
left,right=np.hsplit(grid,[2])
print(left)
print(right)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[99 99 99]
 [ 1  2  3]
 [ 4  5  6]]
[[ 1  2  3 99]
 [ 4  5  6 99]]
[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
