In [5]:
import array
L=list(range(10))
print(L)

#提供有效率儲存資料在固定型態、資料緩衝區中
A=array.array('i',L) #i表integer
print(A)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [27]:
#從python list中建立陣列

import numpy as np
import array
array1=np.array([1,4,2,5,3])
print(array1)

#NumPy限制所限制所有在陣列中的內容需要同樣的型態。
#如果不合，它將試著自動轉換其形態(例如:整數轉浮點數)
array2=np.array([3.14,4,2,3])
print(array2)

#設定陣列的資料型態
array3=np.array([1,2,3,4,5],dtype='float32')
print(array3)

#設定多個維度
array4=np.array([range(i,i+3) for i in [1,4,7]])
array4

[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[1. 2. 3. 4. 5.]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#從無到有建立陣列
import numpy as np

#建立size=10,item全為0之陣列
array5=np.zeros(10,dtype=int)
print(array5)

#建立內容全為1之3*5的浮點數陣列
array6=np.ones((3,5),dtype=float)
print(array6)

#建立內容全為12.76(可以自己設定)之3*5的陣列
array7=np.full((2,4),12.76)
print(array7)

#建立0到20以2為間隔的陣列
array8=np.arange(0,20,2)
print(array8)

#建立一個5個值之陣列，平均分布於0到2
array9=np.linspace(0,2,5)
print(array9)

#建立0到1亂數值(平均分布)且為3*3之陣列
array10=np.random.random((3,3))
print(array10)

#建立3*3之陣列，內容為常態分布，且為平均0標準差1
array11=np.random.normal(0,1,(3,3))
print(array11)

#建立3*3陣列內容為隨機0到9
array12=np.random.randint(0,10,(3,3))
print(array12)

#建立3*3單位矩陣
array13=np.eye(3)
print(array13)

#建立一個3個整數(未初始化)的陣列，所以那些數字本來就在那裡
array14=np.empty(10)
print(array14)

#字串指定型態
array15=np.zeros(10,dtype='int16')
print(array15)
#NumPy物件指定型態
array16=np.zeros(10,dtype=np.int16)
print(array16)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[12.76 12.76 12.76 12.76]
 [12.76 12.76 12.76 12.76]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2. ]
[[0.10028463 0.14775414 0.08060304]
 [0.89556264 0.11456675 0.85793989]
 [0.81798391 0.36132425 0.56583461]]
[[-0.0380237   0.99695408 -0.43704243]
 [-1.26800954 -0.53848979  0.51421137]
 [ 2.8481728   1.1528334  -0.2989801 ]]
[[6 8 7]
 [5 8 5]
 [8 1 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.e+000 1.e-323 2.e-323 3.e-323 4.e-323 5.e-323 6.e-323 7.e-323 8.e-323
 9.e-323]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
